### ISSUE TITLE
Will this work for Android install on existing EXT4 partition?

### ISSUE THREAD

**Issue by parkerlreed** [me176c-dev/android-efi#1]
I have Android at /opt/AndroidOS/ on an EXT4 partition. I can load from Grub but wanted to use systemd-boot.

This project seems like the shim I need but I am not seeing a way to pass in a subfolder on the options line.

Is this supported?

**Comment by lambdadroid** [comment]
android-efi is designed to load Android boot images from a standard Android partition layout with separate partitions (e.g. a `boot` partition, a `recovery` partition, a `system` partition).

I'm assuming you are talking about an Android x86 installation. Android x86 does not use a standard Android partition layout, therefore you cannot use android-efi to boot it. However, if you take a closer look at the standard GRUB configuration, and make sure that your kernel is on a FAT32 partition, you can probably boot into Android directly from systemd-boot, without the need for android-efi.

**Comment by parkerlreed** [comment]
That's the issue I ran into and was hoping android-efi was able to solve.

I can put the kernel/initrd/ramdisk on the FAT32 EFI and point systemd-boot to it, but then I'm not sure how to get that to then jump to the EXT4 partition that contains system.sfs

**Comment by lambdadroid** [comment]
I'm not familiar with Android x86's booting process, sorry :( But I'm afraid android-efi is not what you're looking for. Have you tried asking on the Android x86 mailing list? https://groups.google.com/forum/#!forum/android-x86

android-efi could be used if Android x86 wanted to use a standard Android partition layout, but I assume this wouldn't integrate well unless there is always a separate disk for the Android installation.

**Comment by parkerlreed** [comment]
Cheers. Yeah I'll continue to poke around. Thanks for the help.
