### ISSUE TITLE
arm uefi

### ISSUE THREAD

**Issue by luka177** [me176c-dev/android-efi#2]
I am working on new dualboot solution, so i am interested what must be changed here for arm64 devices. i have working edk2 env.

**Comment by stephan-gh** [comment]
I don't know anything about UEFI on ARM, but you would mainly need to replace [`linux.c`](https://github.com/me176c-dev/android-efi/blob/master/linux.c). The EFI handover protocol used there is specific to Linux x86_64. You would need to implement the boot specification for Linux ARM(64).
